import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Scale } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="flex-1 max-w-4xl w-full mx-auto px-4 py-12 text-left">
      <div className="mb-6">
        <Link to="/" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#FF733B] hover:text-[#E6622E] transition">
          <ArrowLeft size={14} /> Back to Homepage
        </Link>
      </div>

      <div className="bg-white rounded-[2.5rem] border border-[#2E1E17]/10 p-8 md:p-10 shadow-xl space-y-8 relative overflow-hidden">
        <div className="absolute right-[-5%] top-[-5%] w-[200px] h-[200px] bg-[#FF733B]/5 rounded-full blur-[40px] pointer-events-none" />

        <div className="space-y-3">
          <span className="text-[10px] font-extrabold uppercase tracking-widest text-[#FF733B] flex items-center gap-1.5">
            <Scale size={12} /> Legal Framework
          </span>
          <h2 className="text-3xl font-normal font-serif text-[#2E1E17] leading-tight">Terms of Service</h2>
          <p className="text-xs text-gray-500 font-semibold max-w-2xl leading-relaxed">
            Please read these Terms of Service carefully before utilizing the DTV School Support online portal services.
          </p>
        </div>

        <div className="space-y-6 text-xs text-[#2E1E17]/80 leading-relaxed font-semibold">
          <section className="space-y-2">
            <h4 className="text-sm font-bold text-[#2E1E17]">1. Portal Account Security</h4>
            <p>
              Login access codes are pre-generated by school administration. Staff and faculty members must safeguard their portal login credentials and password tokens. Sharing login credentials or bypassing role limitations is strictly prohibited.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-sm font-bold text-[#2E1E17]">2. Acceptable Use Policy</h4>
            <p>
              Users are expected to interact with the platform in a responsible and respectful manner. Grade alterations, unauthorized syllabus tampering, student record edits, or malicious actions targeting the school server logs will result in immediate suspension and disciplinary action.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-sm font-bold text-[#2E1E17]">3. Educational Resources</h4>
            <p>
              All academic course materials, curriculum guidelines, exam papers, syllabus structures, and school profiles hosted on this platform are intellectual property of DTV School Support.
            </p>
          </section>

          <section className="space-y-2">
            <h4 className="text-sm font-bold text-[#2E1E17]">4. Amendments to Services</h4>
            <p>
              The school administration reserves the right to modify term schedules, academic calendars, fee policies, and grading parameters as per board guidelines.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
